name: React Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.16.0, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: CI=false npm install
    # - run: echo "Dependencies Installation Completed Successfully..."
    # - run: |
    #     CI=false npm run build
    #     echo "Build Completed Successfully..."
    - name: Build Main React Project1
      run: |
        echo "Running..."
        CI=false npm install
        CI=false npm run build --if-present
        echo "Completed..."
