name: React Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # runs-on: [ubuntu-latest, windows-latest]

    strategy:
      matrix:
        # node-version: [14.x, 16.16.0, 18.x]
        node-version: [16.16.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: CI=false npm install
    # - run: CI=false npm ci
    - run: echo "Dependencies Installation Completed Successfully..."
    - run: |
        echo "Build Started..."
        CI=false npm run build --if-present
        echo "Build Completed Successfully..."
    - name: Install React Dependencies & Build
      run: |
        echo "Deploy to Github Pages..."
        CI=false npm run deploy
        echo "Completed..."

    - name: GitHub Pages
      uses: actions/configure-pages@v3.0.6
      with:
        build: build
        token: ${{ github.token }}
