name: React Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # runs-on: [ubuntu-latest, windows-latest]

    env:
      ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}

    strategy:
      matrix:
        # node-version: [14.x, 16.16.0, 18.x]
        node-version: [16.16.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node

    - run: CI=false npm install
    # - run: CI=false npm ci
    - run: echo "Dependencies Installation Completed Successfully..."
    - run: |
        echo "Build Started..."
        CI=false npm run build --if-present
        echo "Build Completed Successfully..."
        mkdir staging && cp -r build/** staging
        echo "Copying the Build folder Completed Successfully..."

    - name: Persist workflow as artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: staging

    - name: GitHub Pages
      uses: actions/configure-pages@v3.0.6
      with:
        build: build
        token: ${{ github.token }}
        author: Younes ERRAJI <younes.erraji8@gmail.com>

    # - name: Deploy GitHub Pages site
    #   uses: actions/deploy-pages@v1.2.9
    #   with:
    #     # GitHub token
    #     token: ${{ github.token }}
    #     timeout: 600000
    #     error_count: 10
    #     author: Younes ERRAJI <younes.erraji8@gmail.com>
